// <auto-generated />
using System;
using M8MusicAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace M8MusicAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110014912_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("M8MusicAPI.Infrastructure.Persistence.Models.Avaliacao", b =>
                {
                    b.Property<Guid>("IdAvalicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("IdMusic")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Nota")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdAvalicao");

                    b.HasIndex("ClienteId");

                    b.HasIndex("IdMusic");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("M8MusicAPI.Infrastructure.Persistence.Models.Cliente", b =>
                {
                    b.Property<Guid>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)");

                    b.Property<string>("NmCliente")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("M8MusicAPI.Models.Music", b =>
                {
                    b.Property<Guid>("idMusic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("artista")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("idMusic");

                    b.ToTable("Musics");
                });

            modelBuilder.Entity("M8MusicAPI.Infrastructure.Persistence.Models.Avaliacao", b =>
                {
                    b.HasOne("M8MusicAPI.Infrastructure.Persistence.Models.Cliente", "Cliente")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("M8MusicAPI.Models.Music", "Music")
                        .WithMany("avaliacoes")
                        .HasForeignKey("IdMusic")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Music");
                });

            modelBuilder.Entity("M8MusicAPI.Infrastructure.Persistence.Models.Cliente", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("M8MusicAPI.Models.Music", b =>
                {
                    b.Navigation("avaliacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
